// Accident Management Form Data Constants

export const WORK_SHIFTS = [
  { value: "Gündüz Mesaisi", label: "Gündüz Mesaisi" },
  { value: "Gece Mesaisi", label: "Gece Mesaisi" }
]

export const EVENT_TYPES = [
  { value: "İş Kazası", label: "İş Kazası" },
  { value: "Ramak Kala", label: "Ramak Kala" }
]

export const EVENT_AREAS = [
  { value: "Atık Alanları", label: "Atık Alanları" },
  { value: "Depo Alanları", label: "Depo Alanları" },
  { value: "Genel - Ofis Alanları", label: "Genel - Ofis Alanları" },
  { value: "Hasta Bakım Alanları", label: "Hasta Bakım Alanları" },
  { value: "Teknik Alanlar", label: "Teknik Alanlar" },
  { value: "Diğer Alanlar", label: "Diğer Alanlar" }
]

export const EVENT_PLACES = {
  "Atık Alanları": [
    { value: "Tıbbi Atık Alanı", label: "Tıbbi Atık Alanı" },
    { value: "Tehlikeli Atık Alanı", label: "Tehlikeli Atık Alanı" },
    { value: "Evsel Atık Alanı", label: "Evsel Atık Alanı" },
    { value: "Geri Dönüşüm Alanı", label: "Geri Dönüşüm Alanı" },
    { value: "Radyoaktif Atık Alanı", label: "Radyoaktif Atık Alanı" }
  ],
  "Depo Alanları": [
    { value: "Ameliyathane Depo", label: "Ameliyathane Depo" },
    { value: "Ana Depo", label: "Ana Depo" },
    { value: "Eczane Depo", label: "Eczane Depo" },
    { value: "Kimyasal Malzeme Deposu", label: "Kimyasal Malzeme Deposu" },
    { value: "Mutfak Depo", label: "Mutfak Depo" },
    { value: "Temizlik Depo", label: "Temizlik Depo" }
  ],
  "Genel - Ofis Alanları": [
    { value: "Asansörler", label: "Asansörler" },
    { value: "Bebek Bakım Odası", label: "Bebek Bakım Odası" },
    { value: "Dış Alan-Hastane Bahçesi", label: "Dış Alan-Hastane Bahçesi" },
    { value: "Diğer Ortak Alanlar (Lobi, Koridor vb.)", label: "Diğer Ortak Alanlar (Lobi, Koridor vb.)" },
    { value: "İbadethaneler", label: "İbadethaneler" },
    { value: "İdari Ofisler", label: "İdari Ofisler" },
    { value: "Kafeterya", label: "Kafeterya" },
    { value: "Lojman", label: "Lojman" },
    { value: "Merdivenler / Yürüyen Merdivenler", label: "Merdivenler / Yürüyen Merdivenler" },
    { value: "Otopark", label: "Otopark" },
    { value: "Servis / Şirket Aracı", label: "Servis / Şirket Aracı" },
    { value: "Soyunma Odaları", label: "Soyunma Odaları" },
    { value: "Yemekhane", label: "Yemekhane" }
  ],
  "Hasta Bakım Alanları": [
    { value: "Acil Servis", label: "Acil Servis" },
    { value: "Ameliyathane", label: "Ameliyathane" },
    { value: "Anjiyo Gözlem", label: "Anjiyo Gözlem" },
    { value: "Endoskopi", label: "Endoskopi" },
    { value: "Fizik Tedavi ve Rehabilitasyon Ünitesi", label: "Fizik Tedavi ve Rehabilitasyon Ünitesi" },
    { value: "Kan Alma", label: "Kan Alma" },
    { value: "Kemoterapi-Onkoloji", label: "Kemoterapi-Onkoloji" },
    { value: "Laboratuvar", label: "Laboratuvar" },
    { value: "Merkezi Sterilizasyon Ünitesi", label: "Merkezi Sterilizasyon Ünitesi" },
    { value: "Nükleer Tıp", label: "Nükleer Tıp" },
    { value: "Poliklinik", label: "Poliklinik" },
    { value: "Radyasyon Onkolojisi", label: "Radyasyon Onkolojisi" },
    { value: "Radyoloji", label: "Radyoloji" },
    { value: "Saç Ekimi", label: "Saç Ekimi" },
    { value: "Tüp Bebek (IVF) Ünitesi", label: "Tüp Bebek (IVF) Ünitesi" },
    { value: "Yatan Hasta Servisi ve Hasta Bakım Alanı", label: "Yatan Hasta Servisi ve Hasta Bakım Alanı" },
    { value: "Yoğun Bakım (Erişkin)", label: "Yoğun Bakım (Erişkin)" },
    { value: "Yoğun Bakım (Koroner)", label: "Yoğun Bakım (Koroner)" },
    { value: "Yoğun Bakım (KVC)", label: "Yoğun Bakım (KVC)" },
    { value: "Yoğun Bakım (Pediatri)", label: "Yoğun Bakım (Pediatri)" },
    { value: "Yoğun Bakım (Yenidoğan)", label: "Yoğun Bakım (Yenidoğan)" },
    { value: "Diğer", label: "Diğer" }
  ],
  "Teknik Alanlar": [
    { value: "ADP Alanı", label: "ADP Alanı" },
    { value: "Asansör Makine Dairesi", label: "Asansör Makine Dairesi" },
    { value: "Biyomedikal Ofis / Atölye", label: "Biyomedikal Ofis / Atölye" },
    { value: "Çatı Alanı", label: "Çatı Alanı" },
    { value: "Hidrofor Alanı", label: "Hidrofor Alanı" },
    { value: "Jeneratör Alanı", label: "Jeneratör Alanı" },
    { value: "Kazan Dairesi", label: "Kazan Dairesi" },
    { value: "Klima Santral Alanı", label: "Klima Santral Alanı" },
    { value: "Medikal Gaz Alanı", label: "Medikal Gaz Alanı" },
    { value: "Pano Odası", label: "Pano Odası" },
    { value: "Server Alanı", label: "Server Alanı" },
    { value: "Teknik Ofis / Atölye", label: "Teknik Ofis / Atölye" },
    { value: "Trafo Alanı", label: "Trafo Alanı" },
    { value: "UPS Odası", label: "UPS Odası" },
    { value: "Diğer", label: "Diğer" }
  ],
  "Diğer Alanlar": [
    { value: "Arşiv", label: "Arşiv" },
    { value: "CCTV", label: "CCTV" },
    { value: "Çamaşırhane", label: "Çamaşırhane" },
    { value: "Eczane", label: "Eczane" },
    { value: "Morg", label: "Morg" },
    { value: "Mutfak", label: "Mutfak" },
    { value: "Santral / Çağrı Merkezi", label: "Santral / Çağrı Merkezi" },
    { value: "Diğer", label: "Diğer" }
  ]
}

export const EMPLOYEE_STATUS = [
  { value: "Kadrolu", label: "Kadrolu" },
  { value: "Kadrosuz", label: "Kadrosuz" },
  { value: "Stajyer", label: "Stajyer" },
  { value: "Geçici Taşeron", label: "Geçici Taşeron" },
  { value: "Sürekli Taşeron", label: "Sürekli Taşeron" }
]

export const PROFESSION_GROUPS = [
  { value: "Atık Personeli", label: "Atık Personeli" },
  { value: "Destek Personeli", label: "Destek Personeli" },
  { value: "Estetisyen / Diyetisyen / Fizyoterapist / Psikolog", label: "Estetisyen / Diyetisyen / Fizyoterapist / Psikolog" },
  { value: "Eczacı", label: "Eczacı" },
  { value: "Güvenlik Personeli", label: "Güvenlik Personeli" },
  { value: "Hekim", label: "Hekim" },
  { value: "Hemşire / Ebe / ATT", label: "Hemşire / Ebe / ATT" },
  { value: "İdari Personel", label: "İdari Personel" },
  { value: "Mutfak Personeli", label: "Mutfak Personeli" },
  { value: "Paramedik", label: "Paramedik" },
  { value: "Porter / YP", label: "Porter / YP" },
  { value: "Teknik Personel", label: "Teknik Personel" },
  { value: "Tekniker / Teknisyen", label: "Tekniker / Teknisyen" },
  { value: "Temizlik Personeli", label: "Temizlik Personeli" },
  { value: "Vale / Şoför", label: "Vale / Şoför" },
  { value: "Diğer", label: "Diğer" }
]

export const DEPARTMENTS = [
  { value: "Anlaşmalı Kurumlar Müdürlüğü", label: "Anlaşmalı Kurumlar Müdürlüğü" },
  { value: "Başhekimlik", label: "Başhekimlik" },
  { value: "Bilgi Sistemleri Müdürlüğü", label: "Bilgi Sistemleri Müdürlüğü" },
  { value: "Biyomedikal Müdürlüğü", label: "Biyomedikal Müdürlüğü" },
  { value: "Çağrı Merkezi", label: "Çağrı Merkezi" },
  { value: "Dış Görüntüleme ve İhale Müdürlüğü", label: "Dış Görüntüleme ve İhale Müdürlüğü" },
  { value: "Hasta Bakım Hizmetleri Müdürlüğü", label: "Hasta Bakım Hizmetleri Müdürlüğü" },
  { value: "Hasta Hakları Müdürlüğü", label: "Hasta Hakları Müdürlüğü" },
  { value: "Hekimlik", label: "Hekimlik" },
  { value: "Hukuk Müşavirliği", label: "Hukuk Müşavirliği" },
  { value: "İnsan Kaynakları Müdürlüğü", label: "İnsan Kaynakları Müdürlüğü" },
  { value: "İş Sağlığı ve Güvenliği", label: "İş Sağlığı ve Güvenliği" },
  { value: "Kalite Müdürlüğü", label: "Kalite Müdürlüğü" },
  { value: "Kurumsal Faturalama Müdürlüğü", label: "Kurumsal Faturalama Müdürlüğü" },
  { value: "Kurumsal Tanıtım Müdürlüğü", label: "Kurumsal Tanıtım Müdürlüğü" },
  { value: "Mali İşler Müdürlüğü", label: "Mali İşler Müdürlüğü" },
  { value: "Misafir Hizmetleri Müdürlüğü", label: "Misafir Hizmetleri Müdürlüğü" },
  { value: "Otelcilik Hizmetleri Müdürlüğü", label: "Otelcilik Hizmetleri Müdürlüğü" },
  { value: "Resmi İşlemler ve Ruhsatlandırma Müdürlüğü", label: "Resmi İşlemler ve Ruhsatlandırma Müdürlüğü" },
  { value: "Satınalma Müdürlüğü", label: "Satınalma Müdürlüğü" },
  { value: "Teknik Hizmetler Müdürlüğü", label: "Teknik Hizmetler Müdürlüğü" },
  { value: "Uluslararası Misafir Hizmetleri Müdürlüğü", label: "Uluslararası Misafir Hizmetleri Müdürlüğü" },
  { value: "Üst Yönetim", label: "Üst Yönetim" }
]

export const POSITIONS = [
  { value: "Acil Servis Hemşiresi", label: "Acil Servis Hemşiresi" },
  { value: "Acil Servis Sorumlu Hemşiresi", label: "Acil Servis Sorumlu Hemşiresi" },
  { value: "Acil Servis YP", label: "Acil Servis YP" },
  { value: "Acil Tıp Hekimi", label: "Acil Tıp Hekimi" },
  { value: "Aferez Hemşiresi", label: "Aferez Hemşiresi" },
  { value: "Ağız ve Diş Sağlığı Hekimi", label: "Ağız ve Diş Sağlığı Hekimi" },
  { value: "Ağız ve Diş Sağlığı Teknikeri", label: "Ağız ve Diş Sağlığı Teknikeri" },
  { value: "Ambulans Şoförü", label: "Ambulans Şoförü" },
  { value: "Ameliyathane Depo Görevlisi", label: "Ameliyathane Depo Görevlisi" },
  { value: "Ameliyathane Depo Sorumlusu", label: "Ameliyathane Depo Sorumlusu" },
  { value: "Ameliyathane Depo Uzmanı", label: "Ameliyathane Depo Uzmanı" },
  { value: "Ameliyathane Hemşiresi", label: "Ameliyathane Hemşiresi" },
  { value: "Ameliyathane Sorumlu Hemşiresi", label: "Ameliyathane Sorumlu Hemşiresi" },
  { value: "Ameliyathane Teknikeri", label: "Ameliyathane Teknikeri" },
  { value: "Ameliyathane YP", label: "Ameliyathane YP" },
  { value: "Ana Depo Görevlisi", label: "Ana Depo Görevlisi" },
  { value: "Ana Depo Sorumlusu", label: "Ana Depo Sorumlusu" },
  { value: "Ana Depo Uzman Yardımcısı", label: "Ana Depo Uzman Yardımcısı" },
  { value: "Ana Depo Uzmanı", label: "Ana Depo Uzmanı" },
  { value: "Anestezi Hekimi", label: "Anestezi Hekimi" },
  { value: "Anestezi Teknikeri", label: "Anestezi Teknikeri" },
  { value: "Anestezi Teknisyeni", label: "Anestezi Teknisyeni" },
  { value: "Anestezi ve Reanimasyon Hekimi", label: "Anestezi ve Reanimasyon Hekimi" },
  { value: "Anjio Gözlem Hemşiresi", label: "Anjio Gözlem Hemşiresi" },
  { value: "Anjio Gözlem Sorumlu Hemşiresi", label: "Anjio Gözlem Sorumlu Hemşiresi" },
  { value: "Anjio Gözlem Sorumlu Teknikeri", label: "Anjio Gözlem Sorumlu Teknikeri" },
  { value: "Anjio Gözlem Teknisyeni", label: "Anjio Gözlem Teknisyeni" },
  { value: "Anjio Gözlem YP", label: "Anjio Gözlem YP" },
  { value: "Anlaşmalı Kurumlar Müdür Yardımcısı", label: "Anlaşmalı Kurumlar Müdür Yardımcısı" },
  { value: "Anlaşmalı Kurumlar Müdürü", label: "Anlaşmalı Kurumlar Müdürü" },
  { value: "Anlaşmalı Kurumlar Sorumlusu", label: "Anlaşmalı Kurumlar Sorumlusu" },
  { value: "Anlaşmalı Kurumlar Stajyeri", label: "Anlaşmalı Kurumlar Stajyeri" },
  { value: "Anlaşmalı Kurumlar Uzman Yardımcısı", label: "Anlaşmalı Kurumlar Uzman Yardımcısı" },
  { value: "Anlaşmalı Kurumlar Uzmanı", label: "Anlaşmalı Kurumlar Uzmanı" },
  { value: "Arşiv ve Dokümantasyon Görevlisi", label: "Arşiv ve Dokümantasyon Görevlisi" },
  { value: "Asansör Vatman Görevlisi", label: "Asansör Vatman Görevlisi" },
  { value: "Aşçı", label: "Aşçı" },
  { value: "Aşçı Yardımcısı", label: "Aşçı Yardımcısı" },
  { value: "Ayaktan Misafir Hizmetleri Danışmanı", label: "Ayaktan Misafir Hizmetleri Danışmanı" },
  { value: "Ayaktan Misafir Hizmetleri Sorumlusu", label: "Ayaktan Misafir Hizmetleri Sorumlusu" },
  { value: "Ayaktan Misafir Hizmetleri Takım Lideri", label: "Ayaktan Misafir Hizmetleri Takım Lideri" },
  { value: "Ayaktan Misafir Hizmetleri Temsilcisi", label: "Ayaktan Misafir Hizmetleri Temsilcisi" },
  { value: "Ayaktan Misafir Hizmetleri Yetkilisi", label: "Ayaktan Misafir Hizmetleri Yetkilisi" },
  { value: "Başhekim", label: "Başhekim" },
  { value: "Başhekim Asistanı", label: "Başhekim Asistanı" },
  { value: "Başhekim Yardımcısı", label: "Başhekim Yardımcısı" },
  { value: "Başhekimlik Stajyeri", label: "Başhekimlik Stajyeri" },
  { value: "Bebek Bakım Odası Hemşiresi", label: "Bebek Bakım Odası Hemşiresi" },
  { value: "Bebek Bakım Odası Sorumlu Hemşiresi", label: "Bebek Bakım Odası Sorumlu Hemşiresi" },
  { value: "Bebek Bakım Odası YP", label: "Bebek Bakım Odası YP" },
  { value: "Bellboy", label: "Bellboy" },
  { value: "Beyin ve Sinir Cerrahisi Hekimi", label: "Beyin ve Sinir Cerrahisi Hekimi" },
  { value: "Bilgi Güvenliği Müdürü", label: "Bilgi Güvenliği Müdürü" },
  { value: "Bilgi Güvenliği Sorumlusu", label: "Bilgi Güvenliği Sorumlusu" },
  { value: "Bilgi Sistemleri Görevlisi", label: "Bilgi Sistemleri Görevlisi" },
  { value: "Bilgi Sistemleri Müdür Yardımcısı", label: "Bilgi Sistemleri Müdür Yardımcısı" },
  { value: "Bilgi Sistemleri Müdürü", label: "Bilgi Sistemleri Müdürü" },
  { value: "Bilgi Sistemleri Sorumlusu", label: "Bilgi Sistemleri Sorumlusu" },
  { value: "Bilgi Sistemleri Stajyeri", label: "Bilgi Sistemleri Stajyeri" },
  { value: "Bilgi Sistemleri Uzman Yardımcısı", label: "Bilgi Sistemleri Uzman Yardımcısı" },
  { value: "Bilgi Sistemleri Uzmanı", label: "Bilgi Sistemleri Uzmanı" },
  { value: "Bina Bakım Ustası", label: "Bina Bakım Ustası" },
  { value: "Birim Asistanı", label: "Birim Asistanı" },
  { value: "Biyokimya Hekimi", label: "Biyokimya Hekimi" },
  { value: "Biyokimya Laboratuvarı Biyologu", label: "Biyokimya Laboratuvarı Biyologu" },
  { value: "Biyokimya Laboratuvarı Teknikeri", label: "Biyokimya Laboratuvarı Teknikeri" },
  { value: "Biyokimya Laboratuvarı Teknisyeni", label: "Biyokimya Laboratuvarı Teknisyeni" },
  { value: "Biyomedikal Müdür Yardımcısı", label: "Biyomedikal Müdür Yardımcısı" },
  { value: "Biyomedikal Müdürü", label: "Biyomedikal Müdürü" },
  { value: "Biyomedikal Satınalma Uzmanı", label: "Biyomedikal Satınalma Uzmanı" },
  { value: "Biyomedikal Sorumlusu", label: "Biyomedikal Sorumlusu" },
  { value: "Biyomedikal Stajyeri", label: "Biyomedikal Stajyeri" },
  { value: "Biyomedikal Teknikeri", label: "Biyomedikal Teknikeri" },
  { value: "Biyomedikal Uzman Yardımcısı", label: "Biyomedikal Uzman Yardımcısı" },
  { value: "Biyomedikal Uzmanı", label: "Biyomedikal Uzmanı" },
  { value: "Bordro ve Özlük İşleri Müdür Yardımcısı", label: "Bordro ve Özlük İşleri Müdür Yardımcısı" },
  { value: "Bordro ve Özlük İşleri Müdürü", label: "Bordro ve Özlük İşleri Müdürü" },
  { value: "Bordro ve Özlük İşleri Sorumlusu", label: "Bordro ve Özlük İşleri Sorumlusu" },
  { value: "Bordro ve Özlük İşleri Uzmanı", label: "Bordro ve Özlük İşleri Uzmanı" },
  { value: "Bulaşıkçı", label: "Bulaşıkçı" },
  { value: "Bütçe ve Raporlama Müdür Yardımcısı", label: "Bütçe ve Raporlama Müdür Yardımcısı" },
  { value: "Bütçe ve Raporlama Müdürü", label: "Bütçe ve Raporlama Müdürü" },
  { value: "Bütçe ve Raporlama Sorumlusu", label: "Bütçe ve Raporlama Sorumlusu" },
  { value: "Cari İşlemler Pazarlama ve Operasyon Sorumlusu", label: "Cari İşlemler Pazarlama ve Operasyon Sorumlusu" },
  { value: "Cerrahi Servis Hemşiresi", label: "Cerrahi Servis Hemşiresi" },
  { value: "Cerrahi Servis Sorumlu Hemşiresi", label: "Cerrahi Servis Sorumlu Hemşiresi" },
  { value: "Cerrahi Servis YP", label: "Cerrahi Servis YP" },
  { value: "Check Up Hekimi", label: "Check Up Hekimi" },
  { value: "Check-up Görevlisi", label: "Check-up Görevlisi" },
  { value: "Çağrı Merkezi Eğitim ve Kalite Uzmanı", label: "Çağrı Merkezi Eğitim ve Kalite Uzmanı" },
  { value: "Çağrı Merkezi Müdür Yardımcısı", label: "Çağrı Merkezi Müdür Yardımcısı" },
  { value: "Çağrı Merkezi Müdürü", label: "Çağrı Merkezi Müdürü" },
  { value: "Çağrı Merkezi Müşteri Temsilcisi", label: "Çağrı Merkezi Müşteri Temsilcisi" },
  { value: "Çağrı Merkezi Supervisor", label: "Çağrı Merkezi Supervisor" },
  { value: "Çağrı Merkezi Takım Lideri", label: "Çağrı Merkezi Takım Lideri" },
  { value: "Çamaşırhane Görevlisi", label: "Çamaşırhane Görevlisi" },
  { value: "Çocuk Cerrahisi Hekimi", label: "Çocuk Cerrahisi Hekimi" },
  { value: "Çocuk Gelişim Uzmanı", label: "Çocuk Gelişim Uzmanı" },
  { value: "Çocuk Hematoloji Servis Hemşiresi", label: "Çocuk Hematoloji Servis Hemşiresi" },
  { value: "Çocuk Hematoloji Servis Sorumlu Hemşiresi", label: "Çocuk Hematoloji Servis Sorumlu Hemşiresi" },
  { value: "Çocuk Hematolojisi Hekimi", label: "Çocuk Hematolojisi Hekimi" },
  { value: "Çocuk Hematolojisi Servis YP", label: "Çocuk Hematolojisi Servis YP" },
  { value: "Çocuk İmmünolojisi Hekimi", label: "Çocuk İmmünolojisi Hekimi" },
  { value: "Çocuk Kardiyolojisi Hekimi", label: "Çocuk Kardiyolojisi Hekimi" },
  { value: "Çocuk Psikiyatri Hekimi", label: "Çocuk Psikiyatri Hekimi" },
  { value: "Çocuk Sağlığı ve Hastalıkları Hekimi", label: "Çocuk Sağlığı ve Hastalıkları Hekimi" },
  { value: "Çocuk Servis Hemşiresi", label: "Çocuk Servis Hemşiresi" },
  { value: "Çocuk Servis Sorumlu Hemşiresi", label: "Çocuk Servis Sorumlu Hemşiresi" },
  { value: "Çocuk Servis YP", label: "Çocuk Servis YP" },
  { value: "Dahiliye Servis Hemşiresi", label: "Dahiliye Servis Hemşiresi" },
  { value: "Dahiliye Servis Sorumlu Hemşiresi", label: "Dahiliye Servis Sorumlu Hemşiresi" },
  { value: "Dahiliye Servis YP", label: "Dahiliye Servis YP" },
  { value: "Danışman", label: "Danışman" },
  { value: "Dermatolog", label: "Dermatolog" },
  { value: "Dış Görüntüleme Hizmetleri ve İhale Müdürü", label: "Dış Görüntüleme Hizmetleri ve İhale Müdürü" },
  { value: "Dış Hizmet Hemşiresi", label: "Dış Hizmet Hemşiresi" },
  { value: "Dış Ticaret Operasyon Sorumlusu", label: "Dış Ticaret Operasyon Sorumlusu" },
  { value: "Dil ve Konuşma Terapisti", label: "Dil ve Konuşma Terapisti" },
  { value: "Diş Ünitesi Görevlisi", label: "Diş Ünitesi Görevlisi" },
  { value: "Diyabet Hemşiresi", label: "Diyabet Hemşiresi" },
  { value: "Diyaliz Servis Hemşiresi", label: "Diyaliz Servis Hemşiresi" },
  { value: "Diyaliz Servis Teknikeri", label: "Diyaliz Servis Teknikeri" },
  { value: "Diyaliz Teknikeri", label: "Diyaliz Teknikeri" },
  { value: "Diyetisyen", label: "Diyetisyen" },
  { value: "Ebe", label: "Ebe" },
  { value: "Eczacı", label: "Eczacı" },
  { value: "Eczane Görevlisi", label: "Eczane Görevlisi" },
  { value: "Eczane Teknikeri", label: "Eczane Teknikeri" },
  { value: "Eczane Teknisyeni", label: "Eczane Teknisyeni" },
  { value: "EEG EMG Görevlisi", label: "EEG EMG Görevlisi" },
  { value: "EEG EMG Teknikeri", label: "EEG EMG Teknikeri" },
  { value: "EEG EMG Teknisyeni", label: "EEG EMG Teknisyeni" },
  { value: "Elektrik Sorumlu Teknisyeni", label: "Elektrik Sorumlu Teknisyeni" },
  { value: "Elektrik Teknikeri", label: "Elektrik Teknikeri" },
  { value: "Elektrik Teknisyeni", label: "Elektrik Teknisyeni" },
  { value: "Embriyolog", label: "Embriyolog" },
  { value: "Endokrinoloji ve Metabolizma Hastalıkları Hekimi", label: "Endokrinoloji ve Metabolizma Hastalıkları Hekimi" },
  { value: "Enfeksiyon Hastalıkları Hekimi", label: "Enfeksiyon Hastalıkları Hekimi" },
  { value: "Enfeksiyon Hemşiresi", label: "Enfeksiyon Hemşiresi" },
  { value: "Ergoterapist", label: "Ergoterapist" },
  { value: "Erişkin KİT Aferez Hemşiresi", label: "Erişkin KİT Aferez Hemşiresi" },
  { value: "Erişkin KİT Aferez Teknik Sorumlusu", label: "Erişkin KİT Aferez Teknik Sorumlusu" },
  { value: "Erişkin KİT Aferez Teknikeri", label: "Erişkin KİT Aferez Teknikeri" },
  { value: "Erişkin KİT Servis Hemşiresi", label: "Erişkin KİT Servis Hemşiresi" },
  { value: "Erişkin KİT Servis Sorumlu Hemşiresi", label: "Erişkin KİT Servis Sorumlu Hemşiresi" },
  { value: "Erişkin KİT YP", label: "Erişkin KİT YP" },
  { value: "Erişkin Onkoloji Servis Hemşiresi", label: "Erişkin Onkoloji Servis Hemşiresi" },
  { value: "Erişkin Onkoloji Servis Sorumlu Hemşiresi", label: "Erişkin Onkoloji Servis Sorumlu Hemşiresi" },
  { value: "Erişkin Onkoloji YP", label: "Erişkin Onkoloji YP" },
  { value: "ERP Mali İşler Uzman Yardımcısı", label: "ERP Mali İşler Uzman Yardımcısı" },
  { value: "ERP Sistemleri Uygulama Geliştirme Müdürü", label: "ERP Sistemleri Uygulama Geliştirme Müdürü" },
  { value: "ERP Sistemleri Uygulama Geliştirme Uzmanı", label: "ERP Sistemleri Uygulama Geliştirme Uzmanı" },
  { value: "ERP Süreçleri Analiz ve İş Geliştirme Sorumlusu", label: "ERP Süreçleri Analiz ve İş Geliştirme Sorumlusu" },
  { value: "Estetisyen", label: "Estetisyen" },
  { value: "ESWL Görevlisi", label: "ESWL Görevlisi" },
  { value: "Fizyoterapist", label: "Fizyoterapist" },
  { value: "Güvenlik Görevlisi", label: "Güvenlik Görevlisi" },
  { value: "Hemşire", label: "Hemşire" },
  { value: "Hekim", label: "Hekim" },
  { value: "İdari Personel", label: "İdari Personel" },
  { value: "Tekniker", label: "Tekniker" },
  { value: "Teknisyen", label: "Teknisyen" },
  { value: "Temizlik Personeli", label: "Temizlik Personeli" },
  { value: "Vale", label: "Vale" },
  { value: "Şoför", label: "Şoför" },
  { value: "Diğer", label: "Diğer" }
]

// Helper function to get places based on selected area
export const getEventPlacesByArea = (area: string) => {
  return EVENT_PLACES[area as keyof typeof EVENT_PLACES] || []
}