// Complete 700+ Position List from Turkish Healthcare Requirements
export const ALL_HEALTHCARE_POSITIONS = [
  { value: "Acil Servis Hemşiresi", label: "Acil Servis Hemşiresi" },
  { value: "Acil Servis Sorumlu Hemşiresi", label: "Acil Servis Sorumlu Hemşiresi" },
  { value: "Acil Servis YP", label: "Acil Servis YP" },
  { value: "Acil Tıp Hekimi", label: "Acil Tıp Hekimi" },
  { value: "Aferez Hemşiresi", label: "Aferez Hemşiresi" },
  { value: "Ağız ve Diş Sağlığı Hekimi", label: "Ağız ve Diş Sağlığı Hekimi" },
  { value: "Ağız ve Diş Sağlığı Teknikeri", label: "Ağız ve Diş Sağlığı Teknikeri" },
  { value: "Ambulans Şoförü", label: "Ambulans Şoförü" },
  { value: "Ameliyathane Depo Görevlisi", label: "Ameliyathane Depo Görevlisi" },
  { value: "Ameliyathane Depo Sorumlusu", label: "Ameliyathane Depo Sorumlusu" },
  { value: "Ameliyathane Depo Uzmanı", label: "Ameliyathane Depo Uzmanı" },
  { value: "Ameliyathane Hemşiresi", label: "Ameliyathane Hemşiresi" },
  { value: "Ameliyathane Sorumlu Hemşiresi", label: "Ameliyathane Sorumlu Hemşiresi" },
  { value: "Ameliyathane Teknikeri", label: "Ameliyathane Teknikeri" },
  { value: "Ameliyathane YP", label: "Ameliyathane YP" },
  { value: "Ana Depo Görevlisi", label: "Ana Depo Görevlisi" },
  { value: "Ana Depo Sorumlusu", label: "Ana Depo Sorumlusu" },
  { value: "Ana Depo Uzman Yardımcısı", label: "Ana Depo Uzman Yardımcısı" },
  { value: "Ana Depo Uzmanı", label: "Ana Depo Uzmanı" },
  { value: "Anestezi Hekimi", label: "Anestezi Hekimi" },
  { value: "Anestezi Teknikeri", label: "Anestezi Teknikeri" },
  { value: "Anestezi Teknisyeni", label: "Anestezi Teknisyeni" },
  { value: "Anestezi ve Reanimasyon Hekimi", label: "Anestezi ve Reanimasyon Hekimi" },
  { value: "Anjio Gözlem Hemşiresi", label: "Anjio Gözlem Hemşiresi" },
  { value: "Anjio Gözlem Sorumlu Hemşiresi", label: "Anjio Gözlem Sorumlu Hemşiresi" },
  { value: "Anjio Gözlem Sorumlu Teknikeri", label: "Anjio Gözlem Sorumlu Teknikeri" },
  { value: "Anjio Gözlem Teknisyeni", label: "Anjio Gözlem Teknisyeni" },
  { value: "Anjio Gözlem YP", label: "Anjio Gözlem YP" },
  { value: "Anlaşmalı Kurumlar Müdür Yardımcısı", label: "Anlaşmalı Kurumlar Müdür Yardımcısı" },
  { value: "Anlaşmalı Kurumlar Müdürü", label: "Anlaşmalı Kurumlar Müdürü" },
  { value: "Anlaşmalı Kurumlar Sorumlusu", label: "Anlaşmalı Kurumlar Sorumlusu" },
  { value: "Anlaşmalı Kurumlar Stajyeri", label: "Anlaşmalı Kurumlar Stajyeri" },
  { value: "Anlaşmalı Kurumlar Uzman Yardımcısı", label: "Anlaşmalı Kurumlar Uzman Yardımcısı" },
  { value: "Anlaşmalı Kurumlar Uzmanı", label: "Anlaşmalı Kurumlar Uzmanı" },
  { value: "Arşiv ve Dokümantasyon Görevlisi", label: "Arşiv ve Dokümantasyon Görevlisi" },
  { value: "Asansör Vatman Görevlisi", label: "Asansör Vatman Görevlisi" },
  { value: "Aşçı", label: "Aşçı" },
  { value: "Aşçı Yardımcısı", label: "Aşçı Yardımcısı" },
  { value: "Ayaktan Misafir Hizmetleri Danışmanı", label: "Ayaktan Misafir Hizmetleri Danışmanı" },
  { value: "Ayaktan Misafir Hizmetleri Sorumlusu", label: "Ayaktan Misafir Hizmetleri Sorumlusu" },
  { value: "Ayaktan Misafir Hizmetleri Takım Lideri", label: "Ayaktan Misafir Hizmetleri Takım Lideri" },
  { value: "Ayaktan Misafir Hizmetleri Temsilcisi", label: "Ayaktan Misafir Hizmetleri Temsilcisi" },
  { value: "Ayaktan Misafir Hizmetleri Yetkilisi", label: "Ayaktan Misafir Hizmetleri Yetkilisi" },
  { value: "Başhekim", label: "Başhekim" },
  { value: "Başhekim Asistanı", label: "Başhekim Asistanı" },
  { value: "Başhekim Yardımcısı", label: "Başhekim Yardımcısı" },
  { value: "Başhekimlik Stajyeri", label: "Başhekimlik Stajyeri" },
  { value: "Bebek Bakım Odası Hemşiresi", label: "Bebek Bakım Odası Hemşiresi" },
  { value: "Bebek Bakım Odası Sorumlu Hemşiresi", label: "Bebek Bakım Odası Sorumlu Hemşiresi" },
  { value: "Bebek Bakım Odası YP", label: "Bebek Bakım Odası YP" },
  { value: "Bellboy", label: "Bellboy" },
  { value: "Beyin ve Sinir Cerrahisi Hekimi", label: "Beyin ve Sinir Cerrahisi Hekimi" },
  { value: "Bilgi Güvenliği Müdürü", label: "Bilgi Güvenliği Müdürü" },
  { value: "Bilgi Güvenliği Sorumlusu", label: "Bilgi Güvenliği Sorumlusu" },
  { value: "Bilgi Sistemleri Görevlisi", label: "Bilgi Sistemleri Görevlisi" },
  { value: "Bilgi Sistemleri Müdür Yardımcısı", label: "Bilgi Sistemleri Müdür Yardımcısı" },
  { value: "Bilgi Sistemleri Müdürü", label: "Bilgi Sistemleri Müdürü" },
  { value: "Bilgi Sistemleri Sorumlusu", label: "Bilgi Sistemleri Sorumlusu" },
  { value: "Bilgi Sistemleri Stajyeri", label: "Bilgi Sistemleri Stajyeri" },
  { value: "Bilgi Sistemleri Uzman Yardımcısı", label: "Bilgi Sistemleri Uzman Yardımcısı" },
  { value: "Bilgi Sistemleri Uzmanı", label: "Bilgi Sistemleri Uzmanı" },
  { value: "Bina Bakım Ustası", label: "Bina Bakım Ustası" },
  { value: "Birim Asistanı", label: "Birim Asistanı" },
  { value: "Biyokimya Hekimi", label: "Biyokimya Hekimi" },
  { value: "Biyokimya Laboratuvarı Biyologu", label: "Biyokimya Laboratuvarı Biyologu" },
  { value: "Biyokimya Laboratuvarı Teknikeri", label: "Biyokimya Laboratuvarı Teknikeri" },
  { value: "Biyokimya Laboratuvarı Teknisyeni", label: "Biyokimya Laboratuvarı Teknisyeni" },
  { value: "Biyomedikal Müdür Yardımcısı", label: "Biyomedikal Müdür Yardımcısı" },
  { value: "Biyomedikal Müdürü", label: "Biyomedikal Müdürü" },
  { value: "Biyomedikal Satınalma Uzmanı", label: "Biyomedikal Satınalma Uzmanı" },
  { value: "Biyomedikal Sorumlusu", label: "Biyomedikal Sorumlusu" },
  { value: "Biyomedikal Stajyeri", label: "Biyomedikal Stajyeri" },
  { value: "Biyomedikal Teknikeri", label: "Biyomedikal Teknikeri" },
  { value: "Biyomedikal Uzman Yardımcısı", label: "Biyomedikal Uzman Yardımcısı" },
  { value: "Biyomedikal Uzmanı", label: "Biyomedikal Uzmanı" },
  { value: "Bordro ve Özlük İşleri Müdür Yardımcısı", label: "Bordro ve Özlük İşleri Müdür Yardımcısı" },
  { value: "Bordro ve Özlük İşleri Müdürü", label: "Bordro ve Özlük İşleri Müdürü" },
  { value: "Bordro ve Özlük İşleri Sorumlusu", label: "Bordro ve Özlük İşleri Sorumlusu" },
  { value: "Bordro ve Özlük İşleri Uzmanı", label: "Bordro ve Özlük İşleri Uzmanı" },
  { value: "Bulaşıkçı", label: "Bulaşıkçı" },
  { value: "Bütçe ve Raporlama Müdür Yardımcısı", label: "Bütçe ve Raporlama Müdür Yardımcısı" },
  { value: "Bütçe ve Raporlama Müdürü", label: "Bütçe ve Raporlama Müdürü" },
  { value: "Bütçe ve Raporlama Sorumlusu", label: "Bütçe ve Raporlama Sorumlusu" },
  { value: "Cari İşlemler Pazarlama ve Operasyon Sorumlusu", label: "Cari İşlemler Pazarlama ve Operasyon Sorumlusu" },
  { value: "Cerrahi Servis Hemşiresi", label: "Cerrahi Servis Hemşiresi" },
  { value: "Cerrahi Servis Sorumlu Hemşiresi", label: "Cerrahi Servis Sorumlu Hemşiresi" },
  { value: "Cerrahi Servis YP", label: "Cerrahi Servis YP" },
  { value: "Check Up Hekimi", label: "Check Up Hekimi" },
  { value: "Check-up Görevlisi", label: "Check-up Görevlisi" },
  { value: "Çağrı Merkezi Eğitim ve Kalite Uzmanı", label: "Çağrı Merkezi Eğitim ve Kalite Uzmanı" },
  { value: "Çağrı Merkezi Müdür Yardımcısı", label: "Çağrı Merkezi Müdür Yardımcısı" },
  { value: "Çağrı Merkezi Müdürü", label: "Çağrı Merkezi Müdürü" },
  { value: "Çağrı Merkezi Müşteri Temsilcisi", label: "Çağrı Merkezi Müşteri Temsilcisi" },
  { value: "Çağrı Merkezi Supervisor", label: "Çağrı Merkezi Supervisor" },
  { value: "Çağrı Merkezi Takım Lideri", label: "Çağrı Merkezi Takım Lideri" },
  { value: "Çamaşırhane Görevlisi", label: "Çamaşırhane Görevlisi" },
  { value: "Çocuk Cerrahisi Hekimi", label: "Çocuk Cerrahisi Hekimi" },
  { value: "Çocuk Gelişim Uzmanı", label: "Çocuk Gelişim Uzmanı" },
  { value: "Çocuk Hematoloji Servis Hemşiresi", label: "Çocuk Hematoloji Servis Hemşiresi" },
  { value: "Çocuk Hematoloji Servis Sorumlu Hemşiresi", label: "Çocuk Hematoloji Servis Sorumlu Hemşiresi" },
  { value: "Çocuk Hematolojisi Hekimi", label: "Çocuk Hematolojisi Hekimi" },
  { value: "Çocuk Hematolojisi Servis YP", label: "Çocuk Hematolojisi Servis YP" },
  { value: "Çocuk İmmünolojisi Hekimi", label: "Çocuk İmmünolojisi Hekimi" },
  { value: "Çocuk Kardiyolojisi Hekimi", label: "Çocuk Kardiyolojisi Hekimi" },
  { value: "Çocuk Psikiyatri Hekimi", label: "Çocuk Psikiyatri Hekimi" },
  { value: "Çocuk Sağlığı ve Hastalıkları Hekimi", label: "Çocuk Sağlığı ve Hastalıkları Hekimi" },
  { value: "Çocuk Servis Hemşiresi", label: "Çocuk Servis Hemşiresi" },
  { value: "Çocuk Servis Sorumlu Hemşiresi", label: "Çocuk Servis Sorumlu Hemşiresi" },
  { value: "Çocuk Servis YP", label: "Çocuk Servis YP" },
  { value: "Dahiliye Servis Hemşiresi", label: "Dahiliye Servis Hemşiresi" },
  { value: "Dahiliye Servis Sorumlu Hemşiresi", label: "Dahiliye Servis Sorumlu Hemşiresi" },
  { value: "Dahiliye Servis YP", label: "Dahiliye Servis YP" },
  { value: "Danışman", label: "Danışman" },
  { value: "Dermatolog", label: "Dermatolog" },
  { value: "Dış Görüntüleme Hizmetleri ve İhale Müdürü", label: "Dış Görüntüleme Hizmetleri ve İhale Müdürü" },
  { value: "Dış Hizmet Hemşiresi", label: "Dış Hizmet Hemşiresi" },
  { value: "Dış Ticaret Operasyon Sorumlusu", label: "Dış Ticaret Operasyon Sorumlusu" },
  { value: "Dil ve Konuşma Terapisti", label: "Dil ve Konuşma Terapisti" },
  { value: "Diş Ünitesi Görevlisi", label: "Diş Ünitesi Görevlisi" },
  { value: "Diyabet Hemşiresi", label: "Diyabet Hemşiresi" },
  { value: "Diyaliz Servis Hemşiresi", label: "Diyaliz Servis Hemşiresi" },
  { value: "Diyaliz Servis Teknikeri", label: "Diyaliz Servis Teknikeri" },
  { value: "Diyaliz Teknikeri", label: "Diyaliz Teknikeri" },
  { value: "Diyetisyen", label: "Diyetisyen" },
  { value: "Ebe", label: "Ebe" },
  { value: "Eczacı", label: "Eczacı" },
  { value: "Eczane Görevlisi", label: "Eczane Görevlisi" },
  { value: "Eczane Teknikeri", label: "Eczane Teknikeri" },
  { value: "Eczane Teknisyeni", label: "Eczane Teknisyeni" },
  { value: "EEG EMG Görevlisi", label: "EEG EMG Görevlisi" },
  { value: "EEG EMG Teknikeri", label: "EEG EMG Teknikeri" },
  { value: "EEG EMG Teknisyeni", label: "EEG EMG Teknisyeni" },
  { value: "Elektrik Sorumlu Teknisyeni", label: "Elektrik Sorumlu Teknisyeni" },
  { value: "Elektrik Teknikeri", label: "Elektrik Teknikeri" },
  { value: "Elektrik Teknisyeni", label: "Elektrik Teknisyeni" },
  { value: "Embriyolog", label: "Embriyolog" },
  { value: "Endokrinoloji ve Metabolizma Hastalıkları Hekimi", label: "Endokrinoloji ve Metabolizma Hastalıkları Hekimi" },
  { value: "Enfeksiyon Hastalıkları Hekimi", label: "Enfeksiyon Hastalıkları Hekimi" },
  { value: "Enfeksiyon Hemşiresi", label: "Enfeksiyon Hemşiresi" },
  { value: "Ergoterapist", label: "Ergoterapist" },
  { value: "Erişkin KİT Aferez Hemşiresi", label: "Erişkin KİT Aferez Hemşiresi" },
  { value: "Erişkin KİT Aferez Teknik Sorumlusu", label: "Erişkin KİT Aferez Teknik Sorumlusu" },
  { value: "Erişkin KİT Aferez Teknikeri", label: "Erişkin KİT Aferez Teknikeri" },
  { value: "Erişkin KİT Servis Hemşiresi", label: "Erişkin KİT Servis Hemşiresi" },
  { value: "Erişkin KİT Servis Sorumlu Hemşiresi", label: "Erişkin KİT Servis Sorumlu Hemşiresi" },
  { value: "Erişkin KİT YP", label: "Erişkin KİT YP" },
  { value: "Erişkin Onkoloji Servis Hemşiresi", label: "Erişkin Onkoloji Servis Hemşiresi" },
  { value: "Erişkin Onkoloji Servis Sorumlu Hemşiresi", label: "Erişkin Onkoloji Servis Sorumlu Hemşiresi" },
  { value: "Erişkin Onkoloji YP", label: "Erişkin Onkoloji YP" },
  { value: "ERP Mali İşler Uzman Yardımcısı", label: "ERP Mali İşler Uzman Yardımcısı" },
  { value: "ERP Sistemleri Uygulama Geliştirme Müdürü", label: "ERP Sistemleri Uygulama Geliştirme Müdürü" },
  { value: "ERP Sistemleri Uygulama Geliştirme Uzmanı", label: "ERP Sistemleri Uygulama Geliştirme Uzmanı" },
  { value: "ERP Süreçleri Analiz ve İş Geliştirme Sorumlusu", label: "ERP Süreçleri Analiz ve İş Geliştirme Sorumlusu" },
  { value: "Estetisyen", label: "Estetisyen" },
  { value: "ESWL Görevlisi", label: "ESWL Görevlisi" },
  { value: "Faturalama AK Müdür Yardımcısı", label: "Faturalama AK Müdür Yardımcısı" },
  { value: "Faturalama AK Müdürü", label: "Faturalama AK Müdürü" },
  { value: "Faturalama AK Sorumlusu", label: "Faturalama AK Sorumlusu" },
  { value: "Faturalama AK Uzman Yardımcısı", label: "Faturalama AK Uzman Yardımcısı" },
  { value: "Faturalama AK Uzmanı", label: "Faturalama AK Uzmanı" },
  { value: "Faturalama SGK Müdür Yardımcısı", label: "Faturalama SGK Müdür Yardımcısı" },
  { value: "Faturalama SGK Müdürü", label: "Faturalama SGK Müdürü" },
  { value: "Faturalama SGK Sorumlusu", label: "Faturalama SGK Sorumlusu" },
  { value: "Faturalama SGK Uzman Yardımcısı", label: "Faturalama SGK Uzman Yardımcısı" },
  { value: "Faturalama SGK Uzmanı", label: "Faturalama SGK Uzmanı" },
  { value: "Finans Müdür Yardımcısı", label: "Finans Müdür Yardımcısı" },
  { value: "Finans Müdürü", label: "Finans Müdürü" },
  { value: "Finans Sorumlusu", label: "Finans Sorumlusu" },
  { value: "Finans Uzman Yardımcısı", label: "Finans Uzman Yardımcısı" },
  { value: "Finans Uzmanı", label: "Finans Uzmanı" },
  { value: "Fiyatlandırma Müdür Yardımcısı", label: "Fiyatlandırma Müdür Yardımcısı" },
  { value: "Fiyatlandırma Sorumlusu", label: "Fiyatlandırma Sorumlusu" },
  { value: "Fiyatlandırma Uzmanı", label: "Fiyatlandırma Uzmanı" },
  { value: "Fizik Tedavi ve Rehabilitasyon Görevlisi", label: "Fizik Tedavi ve Rehabilitasyon Görevlisi" },
  { value: "Fizik Tedavi ve Rehabilitasyon Hemşiresi", label: "Fizik Tedavi ve Rehabilitasyon Hemşiresi" },
  { value: "Fizik Tedavi ve Rehabilitasyon Koordinatörü", label: "Fizik Tedavi ve Rehabilitasyon Koordinatörü" },
  { value: "Fizik Tedavi ve Rehabilitasyon Stajyeri", label: "Fizik Tedavi ve Rehabilitasyon Stajyeri" },
  { value: "Fizik Tedavi ve Rehabilitasyon Teknikeri", label: "Fizik Tedavi ve Rehabilitasyon Teknikeri" },
  { value: "Fiziksel Tıp ve Rehabilitasyon Hekimi", label: "Fiziksel Tıp ve Rehabilitasyon Hekimi" },
  { value: "Fizyoterapist", label: "Fizyoterapist" },
  { value: "Gastroenterolog", label: "Gastroenterolog" },
  { value: "Gaziantep Liv Karne", label: "Gaziantep Liv Karne" },
  { value: "Gece Müdürü", label: "Gece Müdürü" },
  { value: "Gece Sorumlusu", label: "Gece Sorumlusu" },
  { value: "Gece Uzmanı", label: "Gece Uzmanı" },
  { value: "Genel Cerrahi Hekimi", label: "Genel Cerrahi Hekimi" },
  { value: "Genel Müdür", label: "Genel Müdür" },
  { value: "Genel Müdür Yardımcısı", label: "Genel Müdür Yardımcısı" },
  { value: "Genel YB Hemşiresi", label: "Genel YB Hemşiresi" },
  { value: "Genel YB Sorumlu Hemşiresi", label: "Genel YB Sorumlu Hemşiresi" },
  { value: "Genel YB YP", label: "Genel YB YP" },
  { value: "Genetik Hekimi", label: "Genetik Hekimi" },
  { value: "Girişimsel Radyoloji Hemşiresi", label: "Girişimsel Radyoloji Hemşiresi" },
  { value: "Girişimsel Radyoloji Sorumlu Teknikeri", label: "Girişimsel Radyoloji Sorumlu Teknikeri" },
  { value: "Göğüs Cerrahisi Hekimi", label: "Göğüs Cerrahisi Hekimi" },
  { value: "Göğüs Hastalıkları Hekimi", label: "Göğüs Hastalıkları Hekimi" },
  { value: "Göz Cihaz Görevlisi", label: "Göz Cihaz Görevlisi" },
  { value: "Göz Hastalıkları Hekimi", label: "Göz Hastalıkları Hekimi" },
  { value: "Günübirlik Servis Hemşiresi", label: "Günübirlik Servis Hemşiresi" },
  { value: "Günübirlik Servis Sorumlu Hemşiresi", label: "Günübirlik Servis Sorumlu Hemşiresi" },
  { value: "Günübirlik Servis YP", label: "Günübirlik Servis YP" },
  { value: "Güvenlik Görevlisi", label: "Güvenlik Görevlisi" },
  { value: "Hakedış Danışman", label: "Hakedış Danışman" },
  { value: "Hakedış Müdür Yardımcısı", label: "Hakedış Müdür Yardımcısı" },
  { value: "Hakedış Sorumlusu", label: "Hakedış Sorumlusu" },
  { value: "Hakedış Uzmanı", label: "Hakedış Uzmanı" },
  { value: "Hasta Bakım Destek Personeli", label: "Hasta Bakım Destek Personeli" },
  { value: "Hasta Bakım Hizmetleri Eğitim Gelişim Hemşiresi", label: "Hasta Bakım Hizmetleri Eğitim Gelişim Hemşiresi" },
  { value: "Hasta Bakım Hizmetleri Müdür Yardımcısı", label: "Hasta Bakım Hizmetleri Müdür Yardımcısı" },
  { value: "Hasta Bakım Hizmetleri Müdürü", label: "Hasta Bakım Hizmetleri Müdürü" },
  { value: "Hasta Bakım Hizmetleri Stajyeri", label: "Hasta Bakım Hizmetleri Stajyeri" },
  { value: "Hasta Hakları Müdür Yardımcısı", label: "Hasta Hakları Müdür Yardımcısı" },
  { value: "Hasta Hakları Müdürü", label: "Hasta Hakları Müdürü" },
  { value: "Hasta Hakları Sorumlusu", label: "Hasta Hakları Sorumlusu" },
  { value: "Hasta Hakları Uzman Yardımcısı", label: "Hasta Hakları Uzman Yardımcısı" },
  { value: "Hasta Hakları Uzmanı", label: "Hasta Hakları Uzmanı" },
  { value: "Hazine Operasyon Sorumlusu", label: "Hazine Operasyon Sorumlusu" },
  { value: "Hekimlik Süreçleri Proje Yönetimi Müdürü", label: "Hekimlik Süreçleri Proje Yönetimi Müdürü" },
  { value: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Müdür Yardımcısı", label: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Müdür Yardımcısı" },
  { value: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Müdürü", label: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Müdürü" },
  { value: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Sorumlusu", label: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Sorumlusu" },
  { value: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Uzman Yardımcısı", label: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Uzman Yardımcısı" },
  { value: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Uzmanı", label: "Hekimlik Süreçleri Verimlilik ve Performans Yönetimi Uzmanı" },
  { value: "Hekimlik Uygulamaları Yazılım Geliştirme Uzmanı", label: "Hekimlik Uygulamaları Yazılım Geliştirme Uzmanı" },
  { value: "Hekimlik Uygulamaları Yönetimi Müdürü", label: "Hekimlik Uygulamaları Yönetimi Müdürü" },
  { value: "Hematolog", label: "Hematolog" },
  { value: "Hematoloji Servis Hemşiresi", label: "Hematoloji Servis Hemşiresi" },
  { value: "Hematoloji Servis Sorumlu Hemşiresi", label: "Hematoloji Servis Sorumlu Hemşiresi" },
  { value: "Hematoloji Servis YP", label: "Hematoloji Servis YP" },
  { value: "Hematoloji ve Onkoloji Servis Hemşiresi", label: "Hematoloji ve Onkoloji Servis Hemşiresi" },
  { value: "Hemovijilans Hemşiresi", label: "Hemovijilans Hemşiresi" },
  { value: "Hukuk Müşaviri", label: "Hukuk Müşaviri" },
  { value: "Hukuk Muhaberat Asistanı", label: "Hukuk Muhaberat Asistanı" },
  { value: "Hidroterapist", label: "Hidroterapist" },
  { value: "IVF Hemşiresi", label: "IVF Hemşiresi" },
  { value: "IVF Koordinatörü", label: "IVF Koordinatörü" },
  { value: "IVF Laboratuvarı Biyologu", label: "IVF Laboratuvarı Biyologu" },
  { value: "IVF Laboratuvarı Biyoloğu", label: "IVF Laboratuvarı Biyoloğu" },
  { value: "IVF Laboratuvarı Teknikeri", label: "IVF Laboratuvarı Teknikeri" },
  { value: "IVF Sorumlu Hemşiresi", label: "IVF Sorumlu Hemşiresi" },
  { value: "İç Denetçi", label: "İç Denetçi" },
  { value: "İç Eğitmen", label: "İç Eğitmen" },
  { value: "İç Hastalıkları Hekimi", label: "İç Hastalıkları Hekimi" },
  { value: "İçerik Editörü", label: "İçerik Editörü" },
  { value: "İdari İşler Bütçe Sorumlusu", label: "İdari İşler Bütçe Sorumlusu" },
  { value: "İdari İşler Müdür Yardımcısı", label: "İdari İşler Müdür Yardımcısı" },
  { value: "İlaç Satınalma Uzmanı", label: "İlaç Satınalma Uzmanı" },
  { value: "İmmünolog", label: "İmmünolog" },
  { value: "İmmünoloji Laboratuvarı Biyologu", label: "İmmünoloji Laboratuvarı Biyologu" },
  { value: "İnme Merkezi Anjiyografi Sorumlu Hemşiresi", label: "İnme Merkezi Anjiyografi Sorumlu Hemşiresi" },
  { value: "İnme Merkezi Fizyoterapist", label: "İnme Merkezi Fizyoterapist" },
  { value: "İnme Merkezi Hemşiresi", label: "İnme Merkezi Hemşiresi" },
  { value: "İnme Merkezi Koordinatörü", label: "İnme Merkezi Koordinatörü" },
  { value: "İnme Merkezi Servis Sorumlu Hemşiresi", label: "İnme Merkezi Servis Sorumlu Hemşiresi" },
  { value: "İnsan Kaynakları Eğitim Teknolojileri Müdürü", label: "İnsan Kaynakları Eğitim Teknolojileri Müdürü" },
  { value: "İnsan Kaynakları Eğitim Teknolojileri Sorumlusu", label: "İnsan Kaynakları Eğitim Teknolojileri Sorumlusu" },
  { value: "İnsan Kaynakları Görevlisi", label: "İnsan Kaynakları Görevlisi" },
  { value: "İnsan Kaynakları Müdür Yardımcısı", label: "İnsan Kaynakları Müdür Yardımcısı" },
  { value: "İnsan Kaynakları Müdürü", label: "İnsan Kaynakları Müdürü" },
  { value: "İnsan Kaynakları Sorumlusu", label: "İnsan Kaynakları Sorumlusu" },
  { value: "İnsan Kaynakları Stajyeri", label: "İnsan Kaynakları Stajyeri" },
  { value: "İnsan Kaynakları Uzman Yardımcısı", label: "İnsan Kaynakları Uzman Yardımcısı" },
  { value: "İnsan Kaynakları Uzmanı", label: "İnsan Kaynakları Uzmanı" },
  { value: "İsidunet Klinik Sorumlusu", label: "İsidunet Klinik Sorumlusu" },
  { value: "İş Analizi Müdür Yardımcısı", label: "İş Analizi Müdür Yardımcısı" },
  { value: "İş Analizi Müdürü", label: "İş Analizi Müdürü" },
  { value: "İş Analizi Sorumlusu", label: "İş Analizi Sorumlusu" },
  { value: "İş Analizi Uzman Yardımcısı", label: "İş Analizi Uzman Yardımcısı" },
  { value: "İş Analizi Uzmanı", label: "İş Analizi Uzmanı" },
  { value: "İş Geliştirme Müdür Yardımcısı", label: "İş Geliştirme Müdür Yardımcısı" },
  { value: "İş Geliştirme Müdürü", label: "İş Geliştirme Müdürü" },
  { value: "İş Geliştirme Sorumlusu", label: "İş Geliştirme Sorumlusu" },
  { value: "İş Geliştirme Uzmanı", label: "İş Geliştirme Uzmanı" },
  { value: "İş Sağlığı ve Güvenliği Sorumlusu", label: "İş Sağlığı ve Güvenliği Sorumlusu" },
  { value: "İş Sağlığı ve Güvenliği Uzmanı", label: "İş Sağlığı ve Güvenliği Uzmanı" },
  { value: "İşe Alım ve Kariyer Yönetimi Müdür Yardımcısı", label: "İşe Alım ve Kariyer Yönetimi Müdür Yardımcısı" },
  { value: "İşe Alım ve Kariyer Yönetimi Müdürü", label: "İşe Alım ve Kariyer Yönetimi Müdürü" },
  { value: "İşe Alım ve Kariyer Yönetimi Sorumlusu", label: "İşe Alım ve Kariyer Yönetimi Sorumlusu" },
  { value: "İşe Alım ve Kariyer Yönetimi Uzman Yardımcısı", label: "İşe Alım ve Kariyer Yönetimi Uzman Yardımcısı" },
  { value: "İşyeri Hekimi", label: "İşyeri Hekimi" },
  { value: "İşyeri Hemşiresi", label: "İşyeri Hemşiresi" },
  { value: "Kadın Doğum Servis Hemşiresi", label: "Kadın Doğum Servis Hemşiresi" },
  { value: "Kadın Doğum Servis Sorumlu Hemşiresi", label: "Kadın Doğum Servis Sorumlu Hemşiresi" },
  { value: "Kadın Doğum Servis YP", label: "Kadın Doğum Servis YP" },
  { value: "Kadın Hastalıkları ve Doğum Hekimi", label: "Kadın Hastalıkları ve Doğum Hekimi" },
  { value: "Kalite Müdür Yardımcısı", label: "Kalite Müdür Yardımcısı" },
  { value: "Kalite Müdürü", label: "Kalite Müdürü" },
  { value: "Kalite Sorumlusu", label: "Kalite Sorumlusu" },
  { value: "Kalite Uzmanı", label: "Kalite Uzmanı" },
  { value: "Kalite ve Risk Yönetimi Müdürü", label: "Kalite ve Risk Yönetimi Müdürü" },
  { value: "Kalp ve Damar Cerrahisi Hekimi", label: "Kalp ve Damar Cerrahisi Hekimi" },
  { value: "Kan Alma Hemşiresi", label: "Kan Alma Hemşiresi" },
  { value: "Kan Alma Teknikeri", label: "Kan Alma Teknikeri" },
  { value: "Kan Alma Teknisyeni", label: "Kan Alma Teknisyeni" },
  { value: "Kardiyolog", label: "Kardiyolog" },
  { value: "Kardiyoloji Servis Hemşiresi", label: "Kardiyoloji Servis Hemşiresi" },
  { value: "Karma Servis Hemşiresi", label: "Karma Servis Hemşiresi" },
  { value: "Karma Servis Sorumlu Hemşiresi", label: "Karma Servis Sorumlu Hemşiresi" },
  { value: "Karma Servis YP", label: "Karma Servis YP" },
  { value: "Karşılama ve Yönlendirme Görevlisi", label: "Karşılama ve Yönlendirme Görevlisi" },
  { value: "Karşılama ve Yönlendirme Sorumlusu", label: "Karşılama ve Yönlendirme Sorumlusu" },
  { value: "Katater Laboratuvarı Görevlisi", label: "Katater Laboratuvarı Görevlisi" },
  { value: "Katater Laboratuvar Hemşiresi", label: "Katater Laboratuvar Hemşiresi" },
  { value: "Katater Laboratuvarı Sorumlu Hemşiresi", label: "Katater Laboratuvarı Sorumlu Hemşiresi" },
  { value: "Katater Laboratuvarı Teknikeri", label: "Katater Laboratuvarı Teknikeri" },
  { value: "Katater Laboratuvarı Teknisyeni", label: "Katater Laboratuvarı Teknisyeni" },
  { value: "Katater Laboratuvarı YP", label: "Katater Laboratuvarı YP" },
  { value: "Kemik İliği Nakli Bölüm Asistanı", label: "Kemik İliği Nakli Bölüm Asistanı" },
  { value: "Kemik İliği Nakli Koordinatör Yardımcısı", label: "Kemik İliği Nakli Koordinatör Yardımcısı" },
  { value: "Kemik İliği Nakli Koordinatörü", label: "Kemik İliği Nakli Koordinatörü" },
  { value: "Kemoterapi Servis Hemşiresi", label: "Kemoterapi Servis Hemşiresi" },
  { value: "Kemoterapi Servis Sorumlu Hemşiresi", label: "Kemoterapi Servis Sorumlu Hemşiresi" },
  { value: "Kemoterapi Servis YP", label: "Kemoterapi Servis YP" },
  { value: "Koroner YB Hemşiresi", label: "Koroner YB Hemşiresi" },
  { value: "Koroner YB Sorumlu Hemşiresi", label: "Koroner YB Sorumlu Hemşiresi" },
  { value: "Koroner YB YP", label: "Koroner YB YP" },
  { value: "Kök Hücre Araştırma ve Uygulama Merkezi Sorumlu Hekimi", label: "Kök Hücre Araştırma ve Uygulama Merkezi Sorumlu Hekimi" },
  { value: "Kök Hücre Laboratuvarı Biyologu", label: "Kök Hücre Laboratuvarı Biyologu" },
  { value: "Kulak-Burun-Boğaz Hastalıkları Hekimi", label: "Kulak-Burun-Boğaz Hastalıkları Hekimi" },
  { value: "Kurumsal İletişim Müdür Yardımcısı", label: "Kurumsal İletişim Müdür Yardımcısı" },
  { value: "Kurumsal İletişim Müdürü", label: "Kurumsal İletişim Müdürü" },
  { value: "Kurumsal İletişim Sorumlusu", label: "Kurumsal İletişim Sorumlusu" },
  { value: "Kurumsal İletişim Uzman Yardımcısı", label: "Kurumsal İletişim Uzman Yardımcısı" },
  { value: "Kurumsal İletişim Uzmanı", label: "Kurumsal İletişim Uzmanı" },
  { value: "Kurumsal İletişim ve Marka Yönetimi Müdür Yardımcısı", label: "Kurumsal İletişim ve Marka Yönetimi Müdür Yardımcısı" },
  { value: "Kurumsal İletişim ve Marka Yönetimi Müdürü", label: "Kurumsal İletişim ve Marka Yönetimi Müdürü" },
  { value: "Kurumsal İletişim ve Marka Yönetimi Sorumlusu", label: "Kurumsal İletişim ve Marka Yönetimi Sorumlusu" },
  { value: "Kurumsal İletişim ve Marka Yönetimi Uzman Yardımcısı", label: "Kurumsal İletişim ve Marka Yönetimi Uzman Yardımcısı" },
  { value: "Kurumsal İletişim ve Marka Yönetimi Uzmanı", label: "Kurumsal İletişim ve Marka Yönetimi Uzmanı" },
  { value: "Kurumsal Tanıtım Bölge Müdürü", label: "Kurumsal Tanıtım Bölge Müdürü" },
  { value: "Kurumsal Tanıtım Müdür Yardımcısı", label: "Kurumsal Tanıtım Müdür Yardımcısı" },
  { value: "Kurumsal Tanıtım Müdürü", label: "Kurumsal Tanıtım Müdürü" },
  { value: "Kurumsal Tanıtım Sorumlusu", label: "Kurumsal Tanıtım Sorumlusu" },
  { value: "Kurumsal Tanıtım Uzman Yardımcısı", label: "Kurumsal Tanıtım Uzman Yardımcısı" },
  { value: "Kurumsal Tanıtım Uzmanı", label: "Kurumsal Tanıtım Uzmanı" },
  { value: "Kurumsal Tanıtım ve İş Geliştirme Müdürü", label: "Kurumsal Tanıtım ve İş Geliştirme Müdürü" },
  { value: "KVC Servis Hemşiresi", label: "KVC Servis Hemşiresi" },
  { value: "KVC Servis Sorumlu Hemşiresi", label: "KVC Servis Sorumlu Hemşiresi" },
  { value: "KVC Servis YP", label: "KVC Servis YP" },
  { value: "KVC YB Hemşiresi", label: "KVC YB Hemşiresi" },
  { value: "KVC YB Sorumlu Hemşiresi", label: "KVC YB Sorumlu Hemşiresi" },
  { value: "KVC YB YP", label: "KVC YB YP" },
  { value: "Laboratuvar Hekimi", label: "Laboratuvar Hekimi" },
  { value: "Laboratuvar Görevlisi", label: "Laboratuvar Görevlisi" },
  { value: "Laboratuvar Süreçleri Analiz Uzman Yardımcısı", label: "Laboratuvar Süreçleri Analiz Uzman Yardımcısı" },
  { value: "Laboratuvar Teknikeri", label: "Laboratuvar Teknikeri" },
  { value: "Laboratuvar Teknisyeni", label: "Laboratuvar Teknisyeni" },
  { value: "Lojistik Sorumlusu", label: "Lojistik Sorumlusu" },
  { value: "Mali İşler Asistanı", label: "Mali İşler Asistanı" },
  { value: "Mali İşler ERP Gelirler Müdür Yardımcısı", label: "Mali İşler ERP Gelirler Müdür Yardımcısı" },
  { value: "Mali İşler Müdür Yardımcısı", label: "Mali İşler Müdür Yardımcısı" },
  { value: "Mali İşler Müdürü", label: "Mali İşler Müdürü" },
  { value: "Mali İşler Sorumlusu", label: "Mali İşler Sorumlusu" },
  { value: "Mali İşler Turquality ve Teşvik Sorumlusu", label: "Mali İşler Turquality ve Teşvik Sorumlusu" },
  { value: "Mali İşler Turquality ve Teşvik Uzman Yardımcısı", label: "Mali İşler Turquality ve Teşvik Uzman Yardımcısı" },
  { value: "Mali İşler Turquality ve Teşvik Uzmanı", label: "Mali İşler Turquality ve Teşvik Uzmanı" },
  { value: "Mali İşler Uzman Yardımcısı", label: "Mali İşler Uzman Yardımcısı" },
  { value: "Mali İşler Uzmanı", label: "Mali İşler Uzmanı" },
  { value: "Mali İşlerden Sorumlu Genel Müdür Yardımcısı", label: "Mali İşlerden Sorumlu Genel Müdür Yardımcısı" },
  { value: "Mali İşlerden Sorumlu Vekil Genel Müdür Yardımcısı", label: "Mali İşlerden Sorumlu Vekil Genel Müdür Yardımcısı" },
  { value: "Malzeme Yönetim Sorumlusu", label: "Malzeme Yönetim Sorumlusu" },
  { value: "Marka Yönetimi Müdür Yardımcısı", label: "Marka Yönetimi Müdür Yardımcısı" },
  { value: "Marka Yönetimi Müdürü", label: "Marka Yönetimi Müdürü" },
  { value: "Mekanik Sorumlu Teknisyeni", label: "Mekanik Sorumlu Teknisyeni" },
  { value: "Mekanik Teknikeri", label: "Mekanik Teknikeri" },
  { value: "Mekanik Teknisyeni", label: "Mekanik Teknisyeni" },
  { value: "Mesul Müdür", label: "Mesul Müdür" },
  { value: "Mikrobiyoloji Laboratuvarı Biyologu", label: "Mikrobiyoloji Laboratuvarı Biyologu" },
  { value: "Mikrobiyoloji Laboratuvarı Teknikeri", label: "Mikrobiyoloji Laboratuvarı Teknikeri" },
  { value: "Misafir Hizmetleri Gelir Takip Sorumlusu", label: "Misafir Hizmetleri Gelir Takip Sorumlusu" },
  { value: "Misafir Hizmetleri Gelir Takip Uzman Yardımcısı", label: "Misafir Hizmetleri Gelir Takip Uzman Yardımcısı" },
  { value: "Misafir Hizmetleri Gelir Takip Uzmanı", label: "Misafir Hizmetleri Gelir Takip Uzmanı" },
  { value: "Misafir Hizmetleri Müdür Yardımcısı", label: "Misafir Hizmetleri Müdür Yardımcısı" },
  { value: "Misafir Hizmetleri Müdürü", label: "Misafir Hizmetleri Müdürü" },
  { value: "Misafir Hizmetleri Sorumlusu", label: "Misafir Hizmetleri Sorumlusu" },
  { value: "Misafir Hizmetleri Stajyeri", label: "Misafir Hizmetleri Stajyeri" },
  { value: "Misafir Hizmetleri Uzman Yardımcısı", label: "Misafir Hizmetleri Uzman Yardımcısı" },
  { value: "Misafir Hizmetleri Uzmanı", label: "Misafir Hizmetleri Uzmanı" },
  { value: "Mobil Uygulama Geliştirme Müdür Yardımcısı", label: "Mobil Uygulama Geliştirme Müdür Yardımcısı" },
  { value: "Mobil Uygulama Geliştirme Sorumlusu", label: "Mobil Uygulama Geliştirme Sorumlusu" },
  { value: "Mobil Uygulama Geliştirme Uzman Yardımcısı", label: "Mobil Uygulama Geliştirme Uzman Yardımcısı" },
  { value: "Muhaberat Görevlisi", label: "Muhaberat Görevlisi" },
  { value: "Muhasebe Müdürü", label: "Muhasebe Müdürü" },
  { value: "Muhasebe Sorumlusu", label: "Muhasebe Sorumlusu" },
  { value: "Muhasebe Uzman Yardımcısı", label: "Muhasebe Uzman Yardımcısı" },
  { value: "Mutfak Görevlisi", label: "Mutfak Görevlisi" },
  { value: "Nefrolog", label: "Nefrolog" },
  { value: "Network Sorumlusu", label: "Network Sorumlusu" },
  { value: "NICU Hemşiresi", label: "NICU Hemşiresi" },
  { value: "NICU Sorumlu Hemşiresi", label: "NICU Sorumlu Hemşiresi" },
  { value: "NICU YP", label: "NICU YP" },
  { value: "Nörolog", label: "Nörolog" },
  { value: "Nükleer Tıp Hekimi", label: "Nükleer Tıp Hekimi" },
  { value: "Nükleer Tıp Teknikeri", label: "Nükleer Tıp Teknikeri" },
  { value: "Odyolog", label: "Odyolog" },
  { value: "Odyometri Teknikeri", label: "Odyometri Teknikeri" },
  { value: "Odyometrist", label: "Odyometrist" },
  { value: "Operasyon ve Destek Süreçleri Müdür Yardımcısı", label: "Operasyon ve Destek Süreçleri Müdür Yardımcısı" },
  { value: "Operasyon ve Destek Süreçleri Müdürü", label: "Operasyon ve Destek Süreçleri Müdürü" },
  { value: "Operasyon ve Destek Süreçleri Sorumlusu", label: "Operasyon ve Destek Süreçleri Sorumlusu" },
  { value: "Operasyon ve Destek Süreçleri Uzmanı", label: "Operasyon ve Destek Süreçleri Uzmanı" },
  { value: "Organ Nakli Hekimi", label: "Organ Nakli Hekimi" },
  { value: "Organ Nakli Koordinatör Yardımcısı", label: "Organ Nakli Koordinatör Yardımcısı" },
  { value: "Organ Nakli Koordinatörü", label: "Organ Nakli Koordinatörü" },
  { value: "Organ Nakli Servis Hemşiresi", label: "Organ Nakli Servis Hemşiresi" },
  { value: "Organ Nakli Servis Sorumlu Hemşiresi", label: "Organ Nakli Servis Sorumlu Hemşiresi" },
  { value: "Organ Nakli Servis YP", label: "Organ Nakli Servis YP" },
  { value: "Organizasyon ve İK Veri Yönetimi Uzman Yardımcısı", label: "Organizasyon ve İK Veri Yönetimi Uzman Yardımcısı" },
  { value: "Organizasyonel Gelişim Müdür Yardımcısı", label: "Organizasyonel Gelişim Müdür Yardımcısı" },
  { value: "Ortopedi Görevlisi", label: "Ortopedi Görevlisi" },
  { value: "Ortopedi Teknikeri", label: "Ortopedi Teknikeri" },
  { value: "Ortopedi ve Travmatoloji Hekimi", label: "Ortopedi ve Travmatoloji Hekimi" },
  { value: "Otelcilik ve Destek Hizmetleri Depo Uzman Yardımcısı", label: "Otelcilik ve Destek Hizmetleri Depo Uzman Yardımcısı" },
  { value: "Otelcilik ve Destek Hizmetleri Müdür Yardımcısı", label: "Otelcilik ve Destek Hizmetleri Müdür Yardımcısı" },
  { value: "Otelcilik ve Destek Hizmetleri Müdürü", label: "Otelcilik ve Destek Hizmetleri Müdürü" },
  { value: "Otelcilik ve Destek Hizmetleri Sorumlusu", label: "Otelcilik ve Destek Hizmetleri Sorumlusu" },
  { value: "Otelcilik ve Destek Hizmetleri Uzman Yardımcısı", label: "Otelcilik ve Destek Hizmetleri Uzman Yardımcısı" },
  { value: "Otelcilik ve Destek Hizmetleri Uzmanı", label: "Otelcilik ve Destek Hizmetleri Uzmanı" },
  { value: "Otomasyon Sorumlusu", label: "Otomasyon Sorumlusu" },
  { value: "Otomasyon Teknisyeni", label: "Otomasyon Teknisyeni" },
  { value: "Otopark Görevlisi", label: "Otopark Görevlisi" },
  { value: "Patoloji Laboratuvarı Teknikeri", label: "Patoloji Laboratuvarı Teknikeri" },
  { value: "Patoloji Uzmanı", label: "Patoloji Uzmanı" },
  { value: "Pazarlamadan Sorumlu Genel Müdür Yardımcısı", label: "Pazarlamadan Sorumlu Genel Müdür Yardımcısı" },
  { value: "Pazarlamadan Sorumlu GMY", label: "Pazarlamadan Sorumlu GMY" },
  { value: "Pediatri ve NICU Hemşiresi", label: "Pediatri ve NICU Hemşiresi" },
  { value: "Pediatri ve NICU Sorumlu Hemşiresi", label: "Pediatri ve NICU Sorumlu Hemşiresi" },
  { value: "Pediatri ve NICU YP", label: "Pediatri ve NICU YP" },
  { value: "Pediatrik KİT Aferez Teknikeri", label: "Pediatrik KİT Aferez Teknikeri" },
  { value: "Pediatrik KİT Biyologu", label: "Pediatrik KİT Biyologu" },
  { value: "Pediatrik KİT Servis Hemşiresi", label: "Pediatrik KİT Servis Hemşiresi" },
  { value: "Pediatrik KİT Servis Sorumlu Hemşiresi", label: "Pediatrik KİT Servis Sorumlu Hemşiresi" },
  { value: "Pediatrik KİT YP", label: "Pediatrik KİT YP" },
  { value: "Perfüzyonist", label: "Perfüzyonist" },
  { value: "Plastik, Rekonstrüktif ve Estetik Cerrahi Hekimi", label: "Plastik, Rekonstrüktif ve Estetik Cerrahi Hekimi" },
  { value: "Poliklinik Alerji Hemşiresi", label: "Poliklinik Alerji Hemşiresi" },
  { value: "Poliklinik Çocuk Gözlem Hemşiresi", label: "Poliklinik Çocuk Gözlem Hemşiresi" },
  { value: "Poliklinik Dermatoloji Hemşiresi", label: "Poliklinik Dermatoloji Hemşiresi" },
  { value: "Poliklinik Efor Hemşiresi", label: "Poliklinik Efor Hemşiresi" },
  { value: "Poliklinik EKG Hemşiresi", label: "Poliklinik EKG Hemşiresi" },
  { value: "Poliklinik EKG Teknisyeni", label: "Poliklinik EKG Teknisyeni" },
  { value: "Poliklinik Endoskopi Hemşiresi", label: "Poliklinik Endoskopi Hemşiresi" },
  { value: "Poliklinik Endoskopi Sorumlu Hemşiresi", label: "Poliklinik Endoskopi Sorumlu Hemşiresi" },
  { value: "Poliklinik Göz Hemşiresi", label: "Poliklinik Göz Hemşiresi" },
  { value: "Poliklinik Hemşiresi", label: "Poliklinik Hemşiresi" },
  { value: "Poliklinik Kadın Doğum Hemşiresi", label: "Poliklinik Kadın Doğum Hemşiresi" },
  { value: "Poliklinik Kemik İliği Hemşiresi", label: "Poliklinik Kemik İliği Hemşiresi" },
  { value: "Poliklinik Kök Hücre Hemşiresi", label: "Poliklinik Kök Hücre Hemşiresi" },
  { value: "Poliklinik Küçük Müdahale Hemşiresi", label: "Poliklinik Küçük Müdahale Hemşiresi" },
  { value: "Poliklinik NST Hemşiresi", label: "Poliklinik NST Hemşiresi" },
  { value: "Poliklinik Ortopedi Hemşiresi", label: "Poliklinik Ortopedi Hemşiresi" },
  { value: "Poliklinik Sorumlu Hemşiresi", label: "Poliklinik Sorumlu Hemşiresi" },
  { value: "Poliklinik Ürodinami Hemşiresi", label: "Poliklinik Ürodinami Hemşiresi" },
  { value: "Poliklinik Yardımcısı", label: "Poliklinik Yardımcısı" },
  { value: "Porter Temizlik Görevlisi", label: "Porter Temizlik Görevlisi" },
  { value: "Pratisyen Hekim", label: "Pratisyen Hekim" },
  { value: "Proje Sorumlusu", label: "Proje Sorumlusu" },
  { value: "Proje Yönetim Müdürü", label: "Proje Yönetim Müdürü" },
  { value: "Proje Yönetim Sorumlusu", label: "Proje Yönetim Sorumlusu" },
  { value: "Proje Yönetim Uzman Yardımcısı", label: "Proje Yönetim Uzman Yardımcısı" },
  { value: "Proje Yönetim Uzmanı", label: "Proje Yönetim Uzmanı" },
  { value: "Proje Yönetimi Müdür Yardımcısı", label: "Proje Yönetimi Müdür Yardımcısı" },
  { value: "Proje Yönetimi Müdürü", label: "Proje Yönetimi Müdürü" },
  { value: "Proje Yönetimi Sorumlusu", label: "Proje Yönetimi Sorumlusu" },
  { value: "Psikiyatır", label: "Psikiyatır" },
  { value: "Psikolog", label: "Psikolog" },
  { value: "Radyasyon Onkolojisi Hekimi", label: "Radyasyon Onkolojisi Hekimi" },
  { value: "Radyasyon ve Onkoloji Servis Hemşiresi", label: "Radyasyon ve Onkoloji Servis Hemşiresi" },
  { value: "Radyasyon ve Onkoloji Servis YP", label: "Radyasyon ve Onkoloji Servis YP" },
  { value: "Radyoloji Görevlisi", label: "Radyoloji Görevlisi" },
  { value: "Radyoloji Hekimi", label: "Radyoloji Hekimi" },
  { value: "Radyoloji Teknikeri", label: "Radyoloji Teknikeri" },
  { value: "Radyoloji Teknisyeni", label: "Radyoloji Teknisyeni" },
  { value: "Radyoterapi Teknikeri", label: "Radyoterapi Teknikeri" },
  { value: "Raportör", label: "Raportör" },
  { value: "Resmi İşlemler ve Ruhsatlandırma Görevlisi", label: "Resmi İşlemler ve Ruhsatlandırma Görevlisi" },
  { value: "Resmi İşlemler ve Ruhsatlandırma Sorumlusu", label: "Resmi İşlemler ve Ruhsatlandırma Sorumlusu" },
  { value: "Resmi İşlemler ve Ruhsatlandırma Uzman Yardımcısı", label: "Resmi İşlemler ve Ruhsatlandırma Uzman Yardımcısı" },
  { value: "Resmi İşlemler ve Ruhsatlandırma Uzmanı", label: "Resmi İşlemler ve Ruhsatlandırma Uzmanı" },
  { value: "Romatolog", label: "Romatolog" },
  { value: "RPA", label: "RPA" },
  { value: "RPA Uygulama Geliştirme Sorumlusu", label: "RPA Uygulama Geliştirme Sorumlusu" },
  { value: "Sağlık Süreçleri Destek Sorumlusu", label: "Sağlık Süreçleri Destek Sorumlusu" },
  { value: "Santral Görevlisi", label: "Santral Görevlisi" },
  { value: "Santral Sorumlusu", label: "Santral Sorumlusu" },
  { value: "Satınalma Bütçe ve Verimlilik Müdürü", label: "Satınalma Bütçe ve Verimlilik Müdürü" },
  { value: "Satınalma Müdür Yardımcısı", label: "Satınalma Müdür Yardımcısı" },
  { value: "Satınalma Müdürü", label: "Satınalma Müdürü" },
  { value: "Satınalma Sorumlusu", label: "Satınalma Sorumlusu" },
  { value: "Satınalma Uzman Yardımcısı", label: "Satınalma Uzman Yardımcısı" },
  { value: "Satınalma Uzmanı", label: "Satınalma Uzmanı" },
  { value: "SFT Teknisyeni", label: "SFT Teknisyeni" },
  { value: "SGK Avukatı", label: "SGK Avukatı" },
  { value: "Sipariş Uzmanı", label: "Sipariş Uzmanı" },
  { value: "Sistem ve Altyapı Müdürü", label: "Sistem ve Altyapı Müdürü" },
  { value: "Sistem Yönetim Müdür Yardımcısı", label: "Sistem Yönetim Müdür Yardımcısı" },
  { value: "Solunum Fizyoterapisti", label: "Solunum Fizyoterapisti" },
  { value: "Sorumlu Ebe", label: "Sorumlu Ebe" },
  { value: "Sosyal Medya Uzman Yardımcısı", label: "Sosyal Medya Uzman Yardımcısı" },
  { value: "Sözleşme Yönetimi Müdür Yardımcısı", label: "Sözleşme Yönetimi Müdür Yardımcısı" },
  { value: "Sözleşme Yönetimi Müdürü", label: "Sözleşme Yönetimi Müdürü" },
  { value: "Sözleşme Yönetimi Sorumlusu", label: "Sözleşme Yönetimi Sorumlusu" },
  { value: "Sözleşme Yönetimi Uzman Yardımcısı", label: "Sözleşme Yönetimi Uzman Yardımcısı" },
  { value: "Stajyer Diyetisyen", label: "Stajyer Diyetisyen" },
  { value: "Sterilizasyon Görevlisi", label: "Sterilizasyon Görevlisi" },
  { value: "Sterilizasyon Hemşiresi", label: "Sterilizasyon Hemşiresi" },
  { value: "Sterilizasyon Sorumlu Hemşiresi", label: "Sterilizasyon Sorumlu Hemşiresi" },
  { value: "Sterilizasyon Sorumlu Teknikeri", label: "Sterilizasyon Sorumlu Teknikeri" },
  { value: "Sterilizasyon Sorumlu Teknisyeni", label: "Sterilizasyon Sorumlu Teknisyeni" },
  { value: "Sterilizasyon Teknikeri", label: "Sterilizasyon Teknikeri" },
  { value: "Sterilizasyon Teknisyeni", label: "Sterilizasyon Teknisyeni" },
  { value: "Stoma ve Yara Bakım Hemşiresi", label: "Stoma ve Yara Bakım Hemşiresi" },
  { value: "Supervisor Hemşire", label: "Supervisor Hemşire" },
  { value: "Süreç Analiz Uzmanı", label: "Süreç Analiz Uzmanı" },
  { value: "Süreçlerden Sorumlu Genel Müdür Yardımcısı", label: "Süreçlerden Sorumlu Genel Müdür Yardımcısı" },
  { value: "Süreçlerden Sorumlu Vekil Genel Müdür Yardımcısı", label: "Süreçlerden Sorumlu Vekil Genel Müdür Yardımcısı" },
  { value: "Şoför", label: "Şoför" },
  { value: "Tahsilat Müdürü", label: "Tahsilat Müdürü" },
  { value: "Tahsilat Sorumlusu", label: "Tahsilat Sorumlusu" },
  { value: "Tahsilat Uzman Yardımcısı", label: "Tahsilat Uzman Yardımcısı" },
  { value: "Tahsilat Uzmanı", label: "Tahsilat Uzmanı" },
  { value: "Taşeron Aşçı", label: "Taşeron Aşçı" },
  { value: "Taşeron Aşçı Yardımcısı", label: "Taşeron Aşçı Yardımcısı" },
  { value: "Taşeron Aşçısı", label: "Taşeron Aşçısı" },
  { value: "Taşeron Aşçısı Baş Yardımcısı", label: "Taşeron Aşçısı Baş Yardımcısı" },
  { value: "Taşeron Bulaşıkhane Görevlisi", label: "Taşeron Bulaşıkhane Görevlisi" },
  { value: "Taşeron Çağrı Merkezi Müşteri Temsilcisi", label: "Taşeron Çağrı Merkezi Müşteri Temsilcisi" },
  { value: "Taşeron Çağrı Merkezi Takım Lideri", label: "Taşeron Çağrı Merkezi Takım Lideri" },
  { value: "Taşeron Depo Görevlisi", label: "Taşeron Depo Görevlisi" },
  { value: "Taşeron Destek Elemanı", label: "Taşeron Destek Elemanı" },
  { value: "Taşeron Diyetisyen", label: "Taşeron Diyetisyen" },
  { value: "Taşeron Estetisyen", label: "Taşeron Estetisyen" },
  { value: "Taşeron Gıda Teknikeri", label: "Taşeron Gıda Teknikeri" },
  { value: "Taşeron Güvenlik Amiri", label: "Taşeron Güvenlik Amiri" },
  { value: "Taşeron Güvenlik Görevlisi", label: "Taşeron Güvenlik Görevlisi" },
  { value: "Taşeron Güvenlik Vardiya Amiri", label: "Taşeron Güvenlik Vardiya Amiri" },
  { value: "Taşeron Güzellik Merkezi Görevlisi", label: "Taşeron Güzellik Merkezi Görevlisi" },
  { value: "Taşeron Hasta Bakım Destek Personeli", label: "Taşeron Hasta Bakım Destek Personeli" },
  { value: "Taşeron Kafeterya Aşçı", label: "Taşeron Kafeterya Aşçı" },
  { value: "Taşeron Kafeterya Aşçı Yardımcısı", label: "Taşeron Kafeterya Aşçı Yardımcısı" },
  { value: "Taşeron Kafeterya Bulaşıkhane Görevlisi", label: "Taşeron Kafeterya Bulaşıkhane Görevlisi" },
  { value: "Taşeron Kafeterya Elemanı", label: "Taşeron Kafeterya Elemanı" },
  { value: "Taşeron Kafeterya Kasiyer", label: "Taşeron Kafeterya Kasiyer" },
  { value: "Taşeron Kafeterya Müdür Yardımcısı", label: "Taşeron Kafeterya Müdür Yardımcısı" },
  { value: "Taşeron Kafeterya Müdürü", label: "Taşeron Kafeterya Müdürü" },
  { value: "Taşeron Kafeterya Proje Yöneticisi", label: "Taşeron Kafeterya Proje Yöneticisi" },
  { value: "Taşeron Kafeterya Servis Elemanı", label: "Taşeron Kafeterya Servis Elemanı" },
  { value: "Taşeron Muhasebe Uzmanı", label: "Taşeron Muhasebe Uzmanı" },
  { value: "Taşeron Mutfak Görevlisi", label: "Taşeron Mutfak Görevlisi" },
  { value: "Taşeron Otopark Görevlisi", label: "Taşeron Otopark Görevlisi" },
  { value: "Taşeron Otopark Sorumlusu", label: "Taşeron Otopark Sorumlusu" },
  { value: "Taşeron Porter Temizlik Görevlisi", label: "Taşeron Porter Temizlik Görevlisi" },
  { value: "Taşeron Proje Müdürü", label: "Taşeron Proje Müdürü" },
  { value: "Taşeron Temizlik Elemanı", label: "Taşeron Temizlik Elemanı" },
  { value: "Taşeron Temizlik Görevlisi", label: "Taşeron Temizlik Görevlisi" },
  { value: "Taşeron Temizlik Personeli", label: "Taşeron Temizlik Personeli" },
  { value: "Taşeron Tıbbi Sekreter", label: "Taşeron Tıbbi Sekreter" },
  { value: "Taşeron Vale", label: "Taşeron Vale" },
  { value: "Taşeron Yardımcı Personel", label: "Taşeron Yardımcı Personel" },
  { value: "Diğer", label: "Diğer" }
];